version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: ofostier/jboss-as:7.1.1
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t ofostier/jboss-as:7.1.1:latest .
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master